name = "cloudflare-project-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Uncomment and configure these when you're ready to deploy
# account_id = "your-account-id"
# workers_dev = true

[env.production]
name = "cloudflare-project-worker-prod"

[env.staging]
name = "cloudflare-project-worker-staging"